### ISSUE TITLE
When trying to make an execution, an error occurs

### ISSUE THREAD

**Issue by Rocket74** [drudge/n8n-nodes-puppeteer#1]
I installed n8n-nodes-puppeteer using the command npm install n8n-nodes-puppeteer and entered into the environment the registered export N8N_CUSTOM_EXTENSIONS="/root/node_modules/n8n-nodes-puppeteer/" after receiving I get an error: "There was a problem executing the workflow:
"Failed to launch the browser process! [0609/151429.665860:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180. TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md " " 
Please help me solve the problem.

![n8n - ⚠️ My workflow 33](https://user-images.githubusercontent.com/97685948/172910834-bfbabc37-4a29-4836-a003-27d422faa8db.png)

**Comment by drudge** [comment]
Hi @Rocket74! I saw you posted on the N8N community forums so I figured I'd link the solution here:

[https://community.n8n.io/t/n8n-nodes-puppeteer-error-please-help-me/14789](https://community.n8n.io/t/n8n-nodes-puppeteer-error-please-help-me/14789)

I do plan to add args support to the node so you can pass things like `--no-sandbox` in the future.
