### ISSUE TITLE
Installation without modifyng n8n dockerfile

### ISSUE THREAD

**Issue by albertopasqualetto** [drudge/n8n-nodes-puppeteer#10]
Is it possible?

**Comment by drudge** [comment]
No

**Comment by albertopasqualetto** [comment]
Sorry for having bothered

**Comment by drudge** [comment]
Hi @albertopasqualetto - I've updated the node and there is now the option to use external browsers to avoid modifying dockerfile. I've also included an update Docker example that should be easier to manage.

https://github.com/drudge/n8n-nodes-puppeteer#n8n-nodes-puppeteer

**Comment by albertopasqualetto** [comment]
@drudge fine! I've just set it up.
