### ISSUE TITLE
Problem in node ‘Puppeteer‘ Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r1045629 is guaranteed to work

### ISSUE THREAD

**Issue by Maki9009** [drudge/n8n-nodes-puppeteer#13]
Im trying to grab a screenshot of one of my websites.

I looked into it and puppeteer seems to be the only non api free version i can do on my personal device / self host.

i installed the latest node, added my url to it and pressed test the node button

it took a really long time to load and then it gave me this error

Problem in node ‘Puppeteer‘
Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r1045629 is guaranteed to work.

im running this n8n on locally on my m1 mac,
but im currently using a Arc browser its chromium based and its the default browser of the device. how can i fix this issue? or does it require me to use chrome? or set it as default on my system?

**Comment by Maki9009** [comment]
So it works on my windows machine - not my mac machine, im wondering if i set this up on a server would it work? 

ALSO i want a functionity for it to waaaait and then take a screen shot its taking one too early i believe

**Comment by drudge** [comment]
I have not tried to use Arc with `puppeteer` before, but my assumption is that the executable path would need to be adjusted for it to find Arc. Once you've identified the path to your Arc, you can adjust it using the **Executable path** option on the node.

In terms of waiting, there are also several options for this:

**Wait Until**: Allows you to change how Puppeteer considers navigation completed.

- `load`: The load event is fired.
- `DOMContentLoaded`: The DOMContentLoaded event is fired.
- `networkidle0`: No more than 0 connections for at least 500 ms.
- `networkidle2`: No more than 2 connections for at least 500 ms.

**Comment by Maki9009** [comment]
hmmm, im wondering though why did it work on my windows PC and not my mac though... interesting. Also i used the all of these idk - if its puppeteer being too fast issue or its not rendering my webpage fully. Basically i want it to render my webpage that has a Tradingview widget on it. it renders parts of it but not the dynamic chart parts of it... and then takes a screenshot. i want everything to get rendered then screenshot. idk what the solution for this to be.

**Comment by Maki9009** [comment]
i want to make a playwright version of this - since that worked for me locally on cmd with a script.... but to make it into a n8n node like how urs work... idk how

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by drudge** [comment]
Check out version v0.8.0 that allows you to execute puppeteer scripts.
