### ISSUE TITLE
Console log in script node

### ISSUE THREAD

**Issue by riekusr** [drudge/n8n-nodes-puppeteer#19]
Hi, I am having a hard time debugging my pupeteer script, console.log() doesn't seem to print anything in the browser console, like i would expect with the code nodes. 

Am i doing something wrong or is this not a feature?

**Comment by drudge** [comment]
Hi @riekusr - v1.1.0 was released and supports `console.log` and many other features of the Code node:

https://github.com/drudge/n8n-nodes-puppeteer/releases/tag/v1.1.0
