### ISSUE TITLE
Error on run node in Docker

### ISSUE THREAD

**Issue by Nakaharaz** [drudge/n8n-nodes-puppeteer#32]
Hi, I'm new using n8n and Docker, and I've been trying to run n8n-nodes-puppeteer on Docker, following the instructions on readme.md

When I've try to run this command: `docker run -it  -p 5678:5678  -v ~/.n8n:/home/node/.n8n n8n-puppeteer` I got an error:

![image](https://github.com/user-attachments/assets/439320a6-36ce-4347-8649-bf24e64b25e9)

This is my folder structure, I'm running a Linux Ubuntu 24.04.1 LTS, in WSL2

![image](https://github.com/user-attachments/assets/d8076b59-34e4-4471-bea5-1521a41d2879)

**Comment by drudge** [comment]
Hi @Nakaharaz,

This issue isn’t related to the Dockerfile itself, but rather to file permissions on the mounted volume. The n8n Docker container runs as UID/GID `1000` (the `node` user), and the current .n8n directory doesn’t have permissions set for that user.

On your host machine, run the following command, then start the container again:

```bash
chown -R 1000:1000 ~/.n8n
```

I’ve also updated the entrypoint to directly use the node installed during the Docker build, so it won’t re-install the custom node on the first run. You can pull the latest version and try again.

**Comment by Nakaharaz** [comment]
Ty so much for the response!

It worked for me!
