### ISSUE TITLE
Community node Installation error.

### ISSUE THREAD

**Issue by AnirudhG07** [drudge/n8n-nodes-puppeteer#38]
Hi, this might not be just particularly an n8n-nodes-puppeteer issue, but I am not able to install the community node for it.

My setup on macOS -
1) Locally hosted n8n v1.69.2, nodejs version 20.10.0
2) Went to install community nodes(no steps between pt 1 and 2), typed `n8n-nodes-puppeteer` and clicked on check box for unverified code.

<img width="1415" alt="image" src="https://github.com/user-attachments/assets/a23b2add-0457-46a0-926a-d1f625a19716">

Now I get this error -
<img width="370" alt="image" src="https://github.com/user-attachments/assets/dac35333-127a-47b7-9cf0-4fb145e4899d">

In my terminal, this comes as output
```
500 Error loading package "n8n-nodes-puppeteer" :Package could not be installed - check logs for details
400 Package name must start with n8n-nodes-
npm command failed
Error loading package "n8n-nodes-youtube-transcript" :Package could not be installed - check logs for details
ResponseError: Error loading package "n8n-nodes-youtube-transcript" :Package could not be installed - check logs for details
    at CommunityPackagesController.installPackage (/usr/local/lib/node_modules/n8n/src/controllers/community-packages.controller.ts:111:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at handler (/usr/local/lib/node_modules/n8n/src/decorators/controller.registry.ts:105:12)
    at /usr/local/lib/node_modules/n8n/src/response-helper.ts:162:17
```

Please help me debug this issue, I am not sure how to proceed further this. Thanks!
(docker installation works by the way, I am not able to do the rpm way)

**Comment by Marimax01** [comment]
Hello,

Same issue for me :/

**Comment by drudge** [comment]
That's correct, @Marimax01. This looks like an issue with the permissions on the directory where community nodes are being installed and not something related to n8n-nodes-puppeteer specifically.
