### ISSUE TITLE
Continue(using error output) setting issues

### ISSUE THREAD

**Issue by AnirudhG07** [drudge/n8n-nodes-puppeteer#43]
Hi, the puppeteer node works great with the browser too!
Bg: when I go to settings and set `Continue(using error output)` from `Stop Workflow`, I see `Success` and `Error` at the end of the node.
Now say, a link is WRONG(does not exist for example) is passed to the puppeteer node, I see an error as expected. But then it is being passed through `Success` line instead of Error.

<img width="1117" alt="image" src="https://github.com/user-attachments/assets/3307d648-8126-49d3-bb66-22234c22a344" />

You can see `1 item` in the Success node.
Here is the input

<img width="886" alt="image" src="https://github.com/user-attachments/assets/5b512f22-ec2c-4c42-a207-84e383c37463" />

Please share why this issue is present, and can the error be passed through the Error one instead of success?

**Comment by drudge** [comment]
This is resolved in v1.3.0 which was just published to npm.

**Comment by AnirudhG07** [comment]
Oh awesome! Thanks. I will update to the latest code.
