### ISSUE TITLE
Extra headers not passed correctly to puppeteer

### ISSUE THREAD

**Issue by arnoo** [drudge/n8n-nodes-puppeteer#45]
Hello,

It looks like extra headers are not passed correctly to puppeteer, as an assertion that the value is a string fails.

![Screenshot_20241219_175655](https://github.com/user-attachments/assets/a5825c72-99cb-4154-8cfa-fde903699faa)

**Comment by drudge** [comment]
This is resolved in v1.3.0 which was just published to npm.

**Comment by arnoo** [comment]
Thanks a lot !
